### ISSUE TITLE
Normalization to -16 LUFS

### ISSUE THREAD

**Issue by swschilke** [dodeco/snap-mp3gain#1]
Hallo, woud it be possible to use mp3gain to do the normalization to -16 LUFS (e.g. for Podcasts) ? If not, could you add the feature (similar to Auphonic or Audacity from version 2.42)

Kind regards

.

**Comment by driesdeschout** [comment]
I am not sure about all mp3gain features, only doing the Snap packaging.
You might want to ask the upstream developers at https://sourceforge.net/projects/mp3gain/
