### ISSUE TITLE
Can't open ... for reading

### ISSUE THREAD

**Issue by Philipp91** [dodeco/snap-mp3gain#2]
When I download the 1.6.2 source code zip from SourceForge and run `make`, mp3gain works fine. When I install the snap with the same version, it fails with `Can't open <the filename I specified> for reading` IF the file is on `/media/$USER/D`, which is an NTFS partition on my HDD, though it still works fine for any files under `~` on my SSD.

So this error only reproduces with the snap. In order to get more details on the error, one can patch line `mp3gain.c:2122` to
```
fprintf(stderr, "Can't oppen %s for reading: %s\n", argv[mainloop], strerror(errno));
```
But obviously I can only do that for my locally compiled version, which works and doesn't throw the error.

**Comment by Philipp91** [comment]
Maybe configuring [removable-media](https://askubuntu.com/a/1228907) could help?

**Comment by driesdeschout** [comment]
I added the removable-media plug to the snap, so you could give it access with 'snap connect mp3gain:removable-media'.
Should be available after the snap updated to the latest version.

**Comment by Philipp91** [comment]
Great, thanks!
